In [3]:
#QUESTION 1
from array import *
def list_array(array_numb):
    numb_list = array_numb.tolist()
    print(numb_list)
  
array_numb = array('i', [45,34,67])
list_array(array_numb)

[45, 34, 67]


In [19]:
#question 2
import numpy as np
l_array = np.array([[25, 17, 17, 86],
                 [28, 55, 66, 77],
                 [47, 52, 89, 45],
                 [78, 58, 92, 41]])
print("la matrice est:")
print(l_array)

trace = np.trace(l_array)
            
print("la somme est:")
print(trace)

la matrice est:
[[25 17 17 86]
 [28 55 66 77]
 [47 52 89 45]
 [78 58 92 41]]
la somme est:
210


In [18]:
#question 3
import numpy as np
ar = np.array([1, 2, 3, 4, 5, 6, 7])
print(ar[ar > 4])

[1 2 3 4 5 6 7]
[5 6 7]


In [21]:
#question 4
import numpy as np
arr1 = np.array([2,4,9,8])
arr2 = np.array([9,3,5,7])
np.add(arr1,arr2)

array([11,  7, 14, 15])

In [23]:
#question 5
import numpy as np
array = np.array([[1,2],[3,4],[5,6]])
mean = array.mean()
print(mean)

3.5
